services:
  cli:
    build:
      context: .
    volumes:
      - ./working_dir:/app/docs
      - ./templates:/app/templates

  # a helper pandoc just to easily properly set the volume for local testing.
  # use with `docker compose run --rm pandoc <insert pandoc args here>`
  pandoc:
    image: pandoc/latex
    volumes:
      - ./working_dir/ssp-render:/data
