#! /usr/bin/env bash

usage="
$0: Copy Component Definition from within the templates directory or from the network

Usage:
    $0 -h
    $0 -n COMPONENT_NAME [-u COMPONENT_URL]

Options:
-h: show help and exit
-n: Local Component Name
-u: Remote Component URL. Required if COMPONENT_NAME is not shipped in templates folder
"

set -e

component_name=""
component_url=""

while getopts "hn:u:" opt; do
    case "$opt" in
        n)
            component_name=${OPTARG}
            ;;
        u)
            component_url=${OPTARG}
            ;;
        h)
            echo "$usage"
            exit 0
            ;;
    esac
done

if [ "$component_name" = "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$component_url" = "" ]; then
    component_url="/app/templates/component-definitions/$component_name/component-definition.json"
fi

trestle import -f "$component_url" -o "$component_name"
