#! /usr/bin/env bash

usage="
$0: Generate control statement markdown for a Component Definition

Usage:
    $0 -h
    $0 -n COMPONENT_NAME [-m MARKDOWN_DIR]

Options:
-h: show help and exit
-n: Component name
-m: Markdown directory. Defaults to COMPONENT_NAME

Notes:
* Will always fully overwrite the markdown directory
"

set -e

markdown=""
component_name=""

while getopts "hn:m:" opt; do
    case "$opt" in
        n)
            component_name=${OPTARG}
            ;;
        m)
            markdown=${OPTARG}
            ;;
        h)
            echo "$usage"
            exit 0
            ;;
    esac
done

if [ "$component_name" = "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$markdown" = "" ]; then
    markdown=$component_name
fi

trestle author component-generate -n "$component_name" -o "$markdown" -fo
