#! /usr/bin/env bash

usage="
$0: Merge SSP OSCAL into a single file

Usage:
    $0 -h
    $0 [-n SYSTEM_NAME]

Options:
-h: show help and exit
-n: System Name. Defaults to 'system-name' value in trestle-config.yaml

Notes:
* Will load defaults from trestle-config.yaml file, if present
"

set -e

source /app/bin/functions.sh
system_name=$(yaml_parse_value 'trestle-config.yaml' 'system-name')

while getopts "hn:" opt; do
    case "$opt" in
        n)
            system_name=${OPTARG}
            ;;
        h)
            echo "$usage"
            exit 0
            ;;
    esac
done

if [ "$system_name" = "" ]; then
    echo "$usage"
    exit 1
fi

ssp_path="system-security-plans/$system_name"

if [ ! -d "$ssp_path" ]; then
    echo "No existing SSP found."
    echo "$usage"
    exit 1
fi

cd "$ssp_path"
trestle merge -e "system-security-plan.*"
