#! /usr/bin/env bash

usage="
$0: Split SSP OSCAL into manageable files

Usage:
    $0 -h
    $0 [-n SYSTEM_NAME]

Options:
-h: show help and exit
-n: System Name. Defaults to 'system-name' value in trestle-config.yaml

Notes:
* Will load defaults from trestle-config.yaml file, if present
"

set -e

source /app/bin/functions.sh
system_name=$(yaml_parse_value 'trestle-config.yaml' 'system-name')

while getopts "hn:" opt; do
    case "$opt" in
        n)
            system_name=${OPTARG}
            ;;
        h)
            echo "$usage"
            exit 0
            ;;
    esac
done

if [ "$system_name" = "" ]; then
    echo "$usage"
    exit 1
fi

ssp_file="system-security-plans/$system_name/system-security-plan.json"
trestle split -f "$ssp_file" -e "system-security-plan.metadata,system-security-plan.system-characteristics,system-security-plan.system-implementation"
